Repository dwyl/envar, pull requests merged in 2022-05, with the labels that each got.

#11 PR: Create dependabot.yml file closes #10
  .github/dependabot.yml
Labels: awaiting-review, T5m

#15 Allow Envar.get to set default value
  lib/envar.ex
  test/envar_test.exs
Labels: enhancement, awaiting-review

#18 PR: Dialyxir runtime false issue #17
  README.md
  mix.exs
Labels: chore, awaiting-review
